# 1. playbook.yml
# This is the main playbook file that includes all the tasks.

---
- name: Setup Nginx and PHP Web Server Environment
  hosts: web_servers
  become: yes
  vars:
    php_packages:
      - php
      - php-fpm
      - php-mysql
      - php-cli
      - php-common
      - php-xml
      - php-json
      - php-mbstring
    firewalld_services:
      - http

  tasks:
    - name: Ensure Nginx and PHP-FPM are installed
      yum:
        name:
          - nginx
          - "{{ php_packages }}"
        state: present
      notify:
        - restart nginx
        - restart php-fpm

    - name: Create Nginx configuration file from template
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx

    - name: Deploy PHP info page
      copy:
        src: files/phpinfo.php
        dest: /usr/share/nginx/html/phpinfo.php
        mode: '0644'

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: true

    - name: Start and enable PHP-FPM
      service:
        name: php-fpm
        state: started
        enabled: true

    - name: Configure firewalld to allow HTTP traffic
      firewalld:
        service: "{{ firewalld_services }}"
        permanent: yes
        state: enabled
        immediate: yes

    - name: Ensure firewalld is running and enabled on boot
      service:
        name: firewalld
        state: started
        enabled: true

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

    - name: restart php-fpm
      service:
        name: php-fpm
        state: restarted
